version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      target: dev
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    networks:
      - app-network
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  app-network:
volumes:
  pgdata:

